services:
  main-service:
    container_name: main-service
    image: main-service
    env_file:
        - .env
    build:
        context: MainService/
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    depends_on:
        main-postgres:
            condition: service_healthy
        mongo-db:
            condition: service_healthy
        rabbitmq:
            condition: service_healthy
    environment:
        PostgreHost: ${POSTGRES_HOST}
        PostgrePort: ${POSTGRES_PORT}
        PostgreDatabase: ${POSTGRES_DB}
        PostgreUser: ${POSTGRES_USER}
        PostgrePassword: ${POSTGRES_PASSWORD}
        MongoConnection: ${MONGO_CONNECTION}
        MongoDatabase: ${MONGO_DB}
        ApiKey: ${API_KEY}
        BaseUrl: ${BASE_URL}
        Model: ${MODEL}
        Issuer: ${ISSUER}
        Audience: ${AUDIENCE}
        AccessSecretKey: ${ACCESS_SECRET_KEY}
        
        RabbitMq__HostName: ${RABBITMQ_HOST}
        RabbitMq__Port: ${RABBITMQ_PORT}
        RabbitMq__UserName: ${RABBITMQ_USER_NAME}
        RabbitMq__Password: ${RABBITMQ_PASSWORD}
        RabbitMq__Exchange: ${RABBITMQ_EXCHANGE}
        RabbitMq__Queue: ${RABBITMQ_QUEUE}
        RabbitMq__RoutingKey: ${RABBITMQ_ROUTING_KEY}
      
  auth-service:
      container_name: auth-service
      image: auth-service
      build:
          context: AuthService/
          dockerfile: Dockerfile
      ports:
          - "5000:5001"
      depends_on:
          - auth-postgres
          - redis
      env_file:
          - .env            
      environment:
          ASPNETCORE_ENVIRONMENT: Development
          ConnectionStrings__DefaultConnection: "Host=auth-postgres;Port=5432;Database=users;Username=postgres;Password=postgres"
          Issuer: ${ISSUER}
          Audience: ${AUDIENCE}
          AccessSecretKey: ${ACCESS_SECRET_KEY}
          AccessExpiresHours: ${ACCESS_EXPIRES_HOURS} 
          RefreshExpiresDays: ${REFRESH_EXPIRES_DAYS} 
          RefreshSecretKey: ${REFRESH_SECRET_KEY}
          RedisHost: ${REDIS_HOST}
          RedisPort: ${REDIS_PORT}
          RedisPassword: ${REDIS_PASSWORD}
          RedisConnectionString: ${REDIS_CONNECTION}
          
  notification-service:
      container_name: notification-service
      build:
          context: NotificationService/
          dockerfile: Dockerfile
      env_file:
          - .env
      environment:
          ASPNETCORE_ENVIRONMENT: Development
          RabbitMq__HostName: ${RABBITMQ_HOST}
          RabbitMq__Port: ${RABBITMQ_PORT}
          RabbitMq__UserName: ${RABBITMQ_USER_NAME}
          RabbitMq__Password: ${RABBITMQ_PASSWORD}
          RabbitMq__Exchange: ${RABBITMQ_EXCHANGE}
          RabbitMq__Queue: ${RABBITMQ_QUEUE}
          RabbitMq__RoutingKey: ${RABBITMQ_ROUTING_KEY}
      depends_on:
          rabbitmq:
              condition: service_healthy
      ports:
          - "7777:7777"

  main-postgres:
    container_name: langtice-main-postgres
    image: postgres:17
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - main-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-postgres:
    image: postgres:17
    container_name: langtice-auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5434:5432" 
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
      - ./db/auth/init:/docker-entrypoint-initdb.d
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres -d users" ]
        interval: 5s
        timeout: 5s
        retries: 10

  mongo-db:
    container_name: langtice-mongo-db
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${MONGO_USER}", "--password", "${MONGO_PASSWORD}", "--authenticationDatabase=admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
      image: redis:7-alpine
      container_name: langtice-redis
      restart: always
      ports:
          - "6379:6379"
      command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
      environment:
          REDIS_PASSWORD: ${REDIS_PASSWORD}
          ConnectionStrings__Redis: ${REDIS_CONNECTION}
      volumes:
          - redis-data:/data
      healthcheck:
          test: [ "CMD", "redis-cli", "ping" ]
          interval: 5s
          timeout: 3s
          retries: 10
        
  rabbitmq:
      image: rabbitmq:4-management
      container_name: rabbitmq
      restart: always
      ports:
          - "5672:5672"
          - "15672:15672"
      environment:
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      healthcheck:
          test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
          interval: 10s
          timeout: 5s
          retries: 10

volumes:
  main-postgres-data:
  auth-postgres-data:
  mongo-db-data:
  redis-data:
