services:
  main-service:
    container_name: main-service
    image: main-service
    env_file:
      - .env
    build:
      context: MainService/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      main-postgres:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      MONGO_CONNECTION: ${MONGO_CONNECTION}
      MONGO_DB: ${MONGO_DB}
      Issuer: ${ISSUER}
      Audience: ${AUDIENCE}
      SecretKey: ${SECRET_KEY}
      ExpiresHours: ${EXPIRES_HOURS}
      ASPNETCORE_ENVIRONMENT: Development
      

  auth-service:
      container_name: auth-service
      image: auth-service
      build:
          context: AuthService/
          dockerfile: Dockerfile
      ports:
          - "5000:5001"
      depends_on:
          - auth-postgres
      env_file:
          - .env            
      environment:
          ASPNETCORE_ENVIRONMENT: Development
          ConnectionStrings__DefaultConnection: "Host=auth-postgres;Port=5432;Database=users;Username=postgres;Password=postgres"
          Issuer: ${ISSUER}
          Audience: ${AUDIENCE}
          SecretKey: ${SECRET_KEY}
          ExpiresHours: ${EXPIRES_HOURS}

  main-postgres:
    container_name: langtice-main-postgres
    image: postgres:17
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - main-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-postgres:
    image: postgres:17
    container_name: langtice-auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5434:5432" 
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
      - ./db/auth/init:/docker-entrypoint-initdb.d
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres -d users" ]
        interval: 5s
        timeout: 5s
        retries: 10

  mongo-db:
    container_name: langtice-mongo-db
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${MONGO_USER}", "--password", "${MONGO_PASSWORD}", "--authenticationDatabase=admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  main-postgres-data:
  auth-postgres-data:
  mongo-db-data:
